Finished new functions: docker_login, docker_login_aws_ecr, docker_login_legacy

diff --git a/src/architecture/linux/ff_docker_functions b/src/architecture/linux/ff_docker_functions
--- a/src/architecture/linux/ff_docker_functions
+++ b/src/architecture/linux/ff_docker_functions
@@ -5,17 +5,30 @@
 #
 
 # Table of contents (generated by: file_toc src/architecture/linux/ff_docker_functions)
-#    - docker_install 
-#    - docker_login 
+## BEGIN UTILITY FUNCTIONS: CONTAINERS
+#    - docker_cleanup 
+#    - docker_container_name_exists 
 #    - docker_ensure 
-#    - docker_is_installed 
-#    - docker_get_installed_version
 #    - docker_ensure_log_to_syslog 
-#    - docker_is_log_to_syslog 
-#    - docker_set_log_to_syslog 
-#    - docker_restart 
-#    - is_every_containers_log_to_syslog 
+#    - docker_get_default_minimum_major_version 
+#    - docker_get_installed_version 
+#    - docker_install 
+#    - docker_is_container_healthy 
 #    - docker_is_container_log_to_syslog 
+#    - docker_is_container_running 
+#    - docker_is_every_container_log_to_syslog 
+#    - docker_is_installed 
+#    - docker_is_log_to_syslog 
+#    - docker_login 
+#    - docker_login_aws_ecr 
+#    - docker_login_legacy 
+#    - docker_minimal_version_check 
+#    - docker_restart 
+#    - docker_restart_containers 
+#    - docker_set_log_to_syslog 
+#    - docker_stop_and_remove_container_by_name 
+#    - docker_volumes_to_containers_list 
+## END UTILITY FUNCTIONS: DOCKERS
 
 ###############################################################################
 # Category: container
@@ -57,19 +70,21 @@ export -f docker_cleanup
 #    fi
 #
 function docker_container_name_exists {
-    CONTAINER_NAME="${1}"
-    # -z - true if the length of string is zero
-    # -n - true if the length of string is nonzero
-    if [ -z "${CONTAINER_NAME}" ]; then
-        error "error_no_container_name_specified"
-        return 2
-    fi
-    CONTAINER_ID=$(docker inspect --format="{{.Id}}" ${CONTAINER_NAME} 2> /dev/null)
-    if [[ "${CONTAINER_ID}" ]]; then
-        return 0
-    else
-        return 1
-    fi
+  
+  CONTAINER_NAME="${1}"
+  # -z - true if the length of string is zero
+  # -n - true if the length of string is nonzero
+  if [ -z "${CONTAINER_NAME}" ]; then
+      error "error_no_container_name_specified"
+      return 2
+  fi
+
+  CONTAINER_ID=$(docker inspect --format="{{.Id}}" ${CONTAINER_NAME} 2> /dev/null)
+  if [[ "${CONTAINER_ID}" ]]; then
+    return 0
+  else
+    return 1
+  fi
 }
 export -f docker_container_name_exists
 
@@ -180,6 +195,7 @@ function docker_install {
   # Check required environment variables are set
   for VARIABLE_NAME in "${REQUIRED_VARIABLES[@]}"; do
     ensure_variable_not_empty "${VARIABLE_NAME}" || {
+      # Dynamically generate an error_code, which include failed variable name (lowercase)
       local ERROR_CODE="$( echo "failed_to_ensure_variable_not_empty_${VARIABLE_NAME}" | tr '[:upper:]' '[:lower:]' )"
       set_state "${FUNCNAME[0]}" "${ERROR_CODE}"
       return 1
@@ -316,7 +332,7 @@ function docker_is_container_log_to_syslog {
   
   set_state "${FUNCNAME[0]}" 'started'
 
-  # Check we got exactly 1 argument
+  # Check number of arguments: must be exactly 1
   [ $# -eq 1 ] || { set_state "${FUNCNAME[0]}" 'error_wrong_number_of_arguments'; return 1; }
   
   # Take argument (container ID or name)
@@ -418,7 +434,6 @@ export -f docker_is_every_container_log_to_syslog
 # and might try to start installing it, which is wrong.. and we lost the root cause of the problem.
 #
 function docker_is_installed {
-
   set_state "${FUNCNAME[0]}" 'started'
   
   # If it not installed, set STATUS=1
@@ -464,6 +479,176 @@ export -f docker_is_log_to_syslog
 
 ###############################################################################
 #
+# Function docker_login() takes 1-3 arguments and login to container repository.
+# It supports 2 cases:
+#   1) "legacy" repositories (requres 3 arguments: FQDN, username and password)
+#   2) AWS ECR (require: FQDN + Amazon secrets)
+#
+# Note: for the AWS ECR there can be 2 or 4 arguments used:
+#   1) only 1 argument: FQDN and the Amazon secrets alrady set via environment variables:
+#        export AWS_ACCESS_KEY_ID=xxx
+#        export AWS_SECRET_ACCESS_KEY=xxx
+#   2) 3 arguments: FQDN, aws_access_key_id and aws_secret_access_key
+#
+# Usage examples for all supported cases:
+#
+#    # Legacy registry
+#    docker_login \
+#      production_docker_registry_legacy_fqdn \
+#      production_docker_registry_legacy_installer_username \
+#      production_docker_registry_legacy_installer_password
+#
+#    # AWS ECR registry (with AWS secrets pre-set via environment)
+#    docker_login \
+#      production_docker_registry_aws_ecr_fqdn \
+#      production_docker_registry_aws_ecr_region
+#
+#    # AWS ECR registry (with AWS secrets passed as arguments)
+#    docker_login \
+#      production_docker_registry_aws_ecr_fqdn \
+#      production_docker_registry_aws_ecr_region \
+#      production_docker_registry_aws_ecr_installer_aws_access_key_id \
+#      production_docker_registry_aws_ecr_installer_aws_secret_access_key
+#
+function docker_login {
+  set_state "${FUNCNAME[0]}" 'started'
+
+  # Check number of arguments: must be either 2, 3 or 4
+  if [ $# -ne 2 ] && [ $# -ne 3 ] && [ $# -ne 4 ]; then
+    set_state "${FUNCNAME[0]}" 'error_wrong_number_of_arguments'
+    return 1
+  fi
+
+  # Get required argument
+  local FQDN="$1"
+
+  # Get secrets
+  FQDN=$( get_secret "${FQDN}" ) || { set_state "${FUNCNAME[0]}" 'failed_to_get_secret_fqdn'; return 1; }
+
+  # Decide if we need docker_login_aws_ecr or docker_login_legacy
+  # Check if FQDN ends with "amazonaws.com"
+  if [[ ${FQDN} =~ amazonaws.com$ ]]; then
+    # Match: use AWS ERC login functino
+    docker_login_aws_ecr "${@}" || { set_state "${FUNCNAME[0]}" 'failed_to_docker_login_aws_ecr'; return 1; }
+
+  else
+    # No match found: use "legacy" login function
+    docker_login_legacy "${@}" || { set_state "${FUNCNAME[0]}" 'failed_to_docker_login_legacy'; return 1; }
+  fi
+
+  set_state "${FUNCNAME[0]}" 'success'
+}
+export -f docker_login
+
+###############################################################################
+#
+# Function supports 2 sets of arguments:
+#   1) 2 arguments:
+#          - production_docker_registry_aws_ecr_fqdn
+#          - production_docker_registry_aws_ecr_region
+#
+#      This case requires the Amazon secrets alrady set via environment variables:
+#        export AWS_ACCESS_KEY_ID=xxx
+#        export AWS_SECRET_ACCESS_KEY=xxx
+#
+#   2) 4 arguments:
+#          - production_docker_registry_aws_ecr_fqdn
+#          - production_docker_registry_aws_ecr_region
+#          - production_docker_registry_aws_ecr_installer_aws_access_key_id
+#          - production_docker_registry_aws_ecr_installer_aws_secret_access_key
+#
+function docker_login_aws_ecr {
+  set_state "${FUNCNAME[0]}" 'started'
+
+  # Check number of arguments: must be either 2 or 4
+  if [ $# -ne 2 ] && [ $# -ne 4 ]; then
+  echo "error_wrong_number_of_arguments: $# "
+    set_state "${FUNCNAME[0]}" 'error_wrong_number_of_arguments'
+    return 1
+  fi
+
+  # Get required arguments
+  local FQDN="$1"
+  local REGION="$2"
+
+  # Check we got non-empty arguments
+  # Define required variables
+  local REQUIRED_VARIABLES=(
+    FQDN
+    REGION
+  )
+
+  # Check required environment variables are set
+  for VARIABLE_NAME in "${REQUIRED_VARIABLES[@]}"; do
+    ensure_variable_not_empty "${VARIABLE_NAME}" || {
+      # Dynamically generate an error_code, which include failed variable name (lowercase)
+      local ERROR_CODE="$( echo "failed_to_ensure_variable_not_empty_${VARIABLE_NAME}" | tr '[:upper:]' '[:lower:]' )"
+      set_state "${FUNCNAME[0]}" "${ERROR_CODE}"
+      return 1
+    }
+  done
+
+  # Get secrets
+  FQDN=$( get_secret "${FQDN}" ) || { set_state "${FUNCNAME[0]}" 'failed_to_get_secret_fqdn'; return 1; }
+  REGION=$( get_secret "${REGION}" ) || { set_state "${FUNCNAME[0]}" 'failed_to_get_secret_region'; return 1; }
+
+  # Get 2 optional arguments:
+  #   - AWS_ACCESS_KEY_ID
+  #   - AWS_SECRET_ACCESS_KEY
+  # If arguments are missing, try to get secrets from environment.
+  if [ $# -eq 4 ]; then
+
+    # AWS secrets were provided as arguments: get arguments
+    local SELECTED_AWS_ACCESS_KEY_ID="$3"
+    local SELECTED_AWS_SECRET_ACCESS_KEY="$4"
+
+    # Get secrets
+    SELECTED_AWS_ACCESS_KEY_ID=$( get_secret "${SELECTED_AWS_ACCESS_KEY_ID}" ) || { set_state "${FUNCNAME[0]}" 'failed_to_get_secret_aws_access_key_id'; return 1; }
+    SELECTED_AWS_SECRET_ACCESS_KEY=$( get_secret "${SELECTED_AWS_SECRET_ACCESS_KEY}" ) || { set_state "${FUNCNAME[0]}" 'failed_to_get_secret_aws_secret_access_key'; return 1; }
+
+  else
+    # AWS secrets were not provided as arguments.
+    # Try to get them from environment or error out.
+    [ ! -z "${AWS_ACCESS_KEY_ID}" ]     || { set_state "${FUNCNAME[0]}" 'failed_to_get_aws_access_key_id_from_environment'; return 1; }
+    [ ! -z "${AWS_SECRET_ACCESS_KEY}" ] || { set_state "${FUNCNAME[0]}" 'failed_to_get_aws_secret_access_key_from_environment'; return 1; }
+    local SELECTED_AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
+    local SELECTED_AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
+  fi
+
+  # At this point both SELECTED_AWS_ACCESS_KEY_ID and SELECTED_AWS_SECRET_ACCESS_KEY must be non-empty strings
+  [ ! -z "${SELECTED_AWS_ACCESS_KEY_ID}" ]     || { set_state "${FUNCNAME[0]}" 'failed_to_get_best_aws_access_key_id'; return 1; }
+  [ ! -z "${SELECTED_AWS_SECRET_ACCESS_KEY}" ] || { set_state "${FUNCNAME[0]}" 'failed_to_get_best_aws_secret_access_key'; return 1; }
+  
+  # Retrieve an authentication token using the GetAuthorizationToken API
+  local TOKEN=$(
+    export AWS_ACCESS_KEY_ID="${SELECTED_AWS_ACCESS_KEY_ID}"
+    export AWS_SECRET_ACCESS_KEY="${SELECTED_AWS_SECRET_ACCESS_KEY}"
+    aws ecr get-login-password --region "${REGION}"
+    ) || { set_state "${FUNCNAME[0]}" 'failed_to_get_token'; return 1; }
+  
+  # Check the token is not blank
+  [ ! -z "${TOKEN}" ] || { set_state "${FUNCNAME[0]}" 'error_got_blank_token'; return 1; }
+
+  # Actual "docker login"
+  # Note: we use piped command here. The exit code of piped commands will be the one of the last command (docker login).
+  # Note: we also collect the output.
+  DOCKER_LOGIN_OUTPUT=$( \
+    echo "${TOKEN}" \
+    | docker login \
+        --username AWS \
+        --password-stdin "${FQDN}" \
+        2>&1
+    ) || { set_state "${FUNCNAME[0]}" 'failed_to_docker_login'; return 1; }
+
+  # Send the "docker login" output to the logger with f-n name tag (simplifies debugging, audit, etc.)
+  echo "${DOCKER_LOGIN_OUTPUT}" | logger -t "${FUNCNAME[0]}"
+
+  set_state "${FUNCNAME[0]}" 'success'
+}
+export -f docker_login_aws_ecr
+
+###############################################################################
+#
 # Function retrieves required named secrets and calls "docker login" to authenticate
 # on the given docker registry.
 #
@@ -476,35 +661,49 @@ export -f docker_is_log_to_syslog
 #   0 - on success
 #   1 - on errror
 #
-# Function also sets state (you can get more details on error by "get_state docker_login" call).
-# Usage example:
-#    docker_login \
+# Function also sets state (you can get more details on error by "get_state docker_login_legacy" call).
+# Usage examples:
+#    docker_login_legacy \
 #      production_docker_registry_general_fqdn \
 #      production_docker_registry_general_installer_username \
 #      production_docker_registry_general_installer_password
 #
-function docker_login {
+function docker_login_legacy {
   set_state "${FUNCNAME[0]}" 'started'
 
-  # Check we get exactly 3 arguments
+  # Check number of arguments: must be exactly 3
   [ $# -eq 3 ] || { set_state "${FUNCNAME[0]}" 'error_wrong_number_of_arguments'; return 1; }
 
   # Get arguments
-  local FQDN_KEY="$1"
-  local USERNAME_KEY="$2"
-  local PASSWORD_KEY="$3"
+  local FQDN="$1"
+  local USERNAME="$2"
+  local PASSWORD="$3"
 
   # Check we got non-empty arguments
-  [ ! -z ${FQDN_KEY} ] || { set_state "${FUNCNAME[0]}" 'error_empty_argument_docker_registry_fqdn'; return 1; }
-  [ ! -z ${USERNAME_KEY} ] || { set_state "${FUNCNAME[0]}" 'error_empty_argument_docker_registry_username'; return 1; }
-  [ ! -z ${PASSWORD_KEY} ] || { set_state "${FUNCNAME[0]}" 'error_empty_argument_docker_registry_password'; return 1; }
+  # Define required variables
+  local REQUIRED_VARIABLES=(
+    FQDN
+    USERNAME
+    PASSWORD
+  )
+
+  # Check required environment variables are set
+  for VARIABLE_NAME in "${REQUIRED_VARIABLES[@]}"; do
+    ensure_variable_not_empty "${VARIABLE_NAME}" || {
+      # Dynamically generate an error_code, which include failed variable name (lowercase)
+      local ERROR_CODE="$( echo "failed_to_ensure_variable_not_empty_${VARIABLE_NAME}" | tr '[:upper:]' '[:lower:]' )"
+      set_state "${FUNCNAME[0]}" "${ERROR_CODE}"
+      return 1
+    }
+  done
 
   # Retrieve actual values by "get_secret()"
-  local FQDN=$( get_secret "${FQDN_KEY}" ) || { set_state "${FUNCNAME[0]}" 'failed_to_get_secret_fqdn'; return 1; }
-  local USERNAME=$( get_secret "${USERNAME_KEY}" ) || { set_state "${FUNCNAME[0]}" 'failed_to_get_secret_username'; return 1; }
-  local PASSWORD=$( get_secret "${PASSWORD_KEY}" ) || { set_state "${FUNCNAME[0]}" 'failed_to_get_secret_password'; return 1; }
+  FQDN=$( get_secret "${FQDN}" ) || { set_state "${FUNCNAME[0]}" 'failed_to_get_secret_fqdn'; return 1; }
+  USERNAME=$( get_secret "${USERNAME}" ) || { set_state "${FUNCNAME[0]}" 'failed_to_get_secret_username'; return 1; }
+  PASSWORD=$( get_secret "${PASSWORD}" ) || { set_state "${FUNCNAME[0]}" 'failed_to_get_secret_password'; return 1; }
   
   # Check if we got non-empty values for container registry: FQDN, username and password
+  # TODO: DRY violation: list attributes as array, iterate, check..
   [ ! -z ${FQDN} ] || { set_state "${FUNCNAME[0]}" 'error_got_empty_fqdn'; return 1; }
   [ ! -z ${USERNAME} ] || { set_state "${FUNCNAME[0]}" 'error_got_empty_username'; return 1; }
   [ ! -z ${PASSWORD} ] || { set_state "${FUNCNAME[0]}" 'error_got_empty_password'; return 1; }
@@ -512,18 +711,20 @@ function docker_login {
   # Actual "docker login"
   # Note: we use piped command here. The exit code of piped commands will be the one of the last command (docker login).
   # Note: we also collect the output.
-  DOCKER_LOGIN_OUTPUT=$( echo "${PASSWORD}" \
-   | docker login \
-       --username "${USERNAME}" \
-       --password-stdin "${FQDN}" \
-       2>&1 ) || { set_state "${FUNCNAME[0]}" 'failed_to_docker_login'; return 1; }
+  DOCKER_LOGIN_OUTPUT=$( \
+    echo "${PASSWORD}" \
+    | docker login \
+        --username "${USERNAME}" \
+        --password-stdin "${FQDN}" \
+        2>&1
+    ) || { set_state "${FUNCNAME[0]}" 'failed_to_docker_login'; return 1; }
 
   # Send the "docker login" output to the logger with f-n name tag (simplifies debugging, audit, etc.)
   echo "${DOCKER_LOGIN_OUTPUT}" | logger -t "${FUNCNAME[0]}"
 
   set_state "${FUNCNAME[0]}" 'success'
 }
-export -f docker_login
+export -f docker_login_legacy
 
 ###############################################################################
 #
