Fix build_tarball: it can not use "set_state()", "abort()" since it is not started by "best user" and there is no easy way to figure out which one is the best (and we do not want to have user hardcoded, btw the user is ff_agent)

diff --git a/build_tarball b/build_tarball
--- a/build_tarball
+++ b/build_tarball
@@ -28,7 +28,7 @@ set -x
 #   - on error: script exits with code 1
 #
 function build_tarball {
-    set_state "${FUNCNAME[0]}" 'started'
+    # set_state "${FUNCNAME[0]}" 'started'
 
     # Check dependencies: define required variables
     local REQUIRED_VARIABLES=(
@@ -40,9 +40,11 @@ function build_tarball {
     # Check required environment variables are set
     for VARIABLE_NAME in "${REQUIRED_VARIABLES[@]}"; do
         ensure_variable_not_empty "${VARIABLE_NAME}" || {
-            local ERROR_CODE="$( echo "failed_to_ensure_variable_not_empty_${VARIABLE_NAME}" | tr '[:upper:]' '[:lower:]' )"
-            set_state "${FUNCNAME[0]}" "${ERROR_CODE}"
-            abort "${ERROR_CODE}"
+            local ERROR_CODE="$( echo "Error: failed_to_ensure_variable_not_empty_${VARIABLE_NAME}" | tr '[:upper:]' '[:lower:]' )"
+            # set_state "${FUNCNAME[0]}" "${ERROR_CODE}"
+            # abort "${ERROR_CODE}"
+            echo "${ERROR_CODE}" >&2
+            exit 1
         }
     done
 
@@ -51,9 +53,9 @@ function build_tarball {
     #      - node
     #      - npm
     #      - tar
-    command_exists node >/dev/null || { echo "Dependency check failed: node not found"; }
-    command_exists npm >/dev/null || { echo "Dependency check failed: npm not found"; }
-    command_exists tar >/dev/null || { echo "Dependency check failed: tar not found"; }
+    command_exists node >/dev/null || { echo "Error: dependency check failed: node not found" >&2; exit 1; }
+    command_exists npm >/dev/null || { echo "Error: dependency check failed: npm not found" >&2; exit 1; }
+    command_exists tar >/dev/null || { echo "Error: dependency check failed: tar not found">&2; exit 1; }
 
     # Define location of temporary folder and tarball filename
     local TARBALL_FILENAME="set_environment-dev.tgz"
@@ -62,21 +64,21 @@ function build_tarball {
     local TEMPORARY_DIR="/tmp"
 
     # We need to "npm install" because of aws-sdk dependency (used by cdn_upload.js)
-    npm i || { set_state "${FUNCNAME[0]}" 'failed_to_npm_install'; abort; }
+    npm install || { echo "Error: failed to 'npm install'" >&2; exit 1; } # { set_state "${FUNCNAME[0]}" 'failed_to_npm_install'; abort; }
 
     # Capture date and build git commit numbers into separate files
-    echo "BUILD_DATE=$(date +%Y%m%d)  # YYYYMMDD" > build_date || { set_state "${FUNCNAME[0]}" 'failed_to_write_build_date'; abort; }
-    echo "BUILD_COMMIT_ID=$(git rev-parse HEAD)"  > build_commit_id || { set_state "${FUNCNAME[0]}" 'failed_to_write_build_commit_id'; abort; }
+    echo "BUILD_DATE=$(date +%Y%m%d)  # YYYYMMDD" > build_date || { echo "Error: failed to write build date" >&2; exit 1; } # { set_state "${FUNCNAME[0]}" 'failed_to_write_build_date'; abort; }
+    echo "BUILD_COMMIT_ID=$(git rev-parse HEAD)"  > build_commit_id || { echo "Error: failed to write build commit id">&2; exit 1; } # { set_state "${FUNCNAME[0]}" 'failed_to_write_build_commit_id'; abort; }
 
     # Delete target tmp "set_environment" folder, otherwise copy will result in wrong folder structure (1 level nested deeper)
     if [ -d "${TEMPORARY_DIR}/set_environment" ]; then
-        rm -fr ${TEMPORARY_DIR}/set_environment || { set_state "${FUNCNAME[0]}" 'failed_to_remove_tmp_folder'; abort; }
+        rm -fr ${TEMPORARY_DIR}/set_environment || { echo "Error: failed to remove temporary folder">&2; exit 1; } # { set_state "${FUNCNAME[0]}" 'failed_to_remove_tmp_folder'; abort; }
     fi
 
     # Before creating tarball: move all files into "set_environment" folder.
     # We do so because while Jenkins buidling the project all the files are located in ugly-looking folder:
     #     /var/jenkins_home/jobs/RedWolfSecurity/jobs/set-environment.ja761g/branches/master/workspace
-    cp -a $(pwd) ${TEMPORARY_DIR}/set_environment || { set_state "${FUNCNAME[0]}" 'failed_to_copy_files'; abort; }
+    cp -a $(pwd) ${TEMPORARY_DIR}/set_environment || { echo "Error: failed to copy files">&2; exit 1; } # { set_state "${FUNCNAME[0]}" 'failed_to_copy_files'; abort; }
 
     # Now we can create tarball which contain just 1 folder 'set_environment'
     # Note on used arguments:
@@ -89,7 +91,7 @@ function build_tarball {
     #      set_environment - last argument is the folder to archive. It does not include full path (like: ${TEMPORARY_DIR}/set_environment)
     #                        because we already specified -C argument.
     #
-    tar -C "${TEMPORARY_DIR}" -czf "${TARBALL_FILENAME}" "set_environment" || { set_state "${FUNCNAME[0]}" 'failed_to_create_tarball'; abort; }
+    tar -C "${TEMPORARY_DIR}" -czf "${TARBALL_FILENAME}" "set_environment" || { echo "Error: failed to create tarball">&2; exit 1; } # { set_state "${FUNCNAME[0]}" 'failed_to_create_tarball'; abort; }
 
     # Upload tarball to S3 so it is available via URL: https:#cdn.redwolfsecurity.com/ff/ff_agent/set_environment.tgz
     node cdn_upload.js \
@@ -99,7 +101,7 @@ function build_tarball {
         "${PRODUCTION_CONTENT_CDN_DISTRIBUTION_ID}" \
          || { set_state "${FUNCNAME[0]}" 'failed_to_cdn_upload'; abort; }
 
-    set_state "${FUNCNAME[0]}" 'success'
+    # set_state "${FUNCNAME[0]}" 'success'
     return 0
 }
 
