More logging

diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,7 +5,7 @@
 [ "$EUID" -ne 0 ] || { echo "❌ Do not run this script as root." >&2; exit 1; }
 
 # Enable tracing (more verbose output)
-export PS4='+ [$(date "+%H:%M:%S")] [${BASH_SOURCE##*/}:${LINENO}] [${FUNCNAME[0]:-MAIN}] '
+export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] [${FUNCNAME[0]:-MAIN}] '
 set -x
 
 # Set optional SERVICE variable. If it is set, then it will be used:
@@ -37,29 +37,35 @@ function install_set_environment () {
 
   # Change directory into the script's directory. This ensure all relative paths working correctly.
   SET_ENVIRONMENT_SCRIPT_DIRECTORY="$( script_directory_get )"
+  log "🟧 top level install script directory is set to: ${SET_ENVIRONMENT_SCRIPT_DIRECTORY}"
+
   export SET_ENVIRONMENT_SCRIPT_DIRECTORY
   cd "${SET_ENVIRONMENT_SCRIPT_DIRECTORY}" || { echo "Error: failed to change directory to ${SET_ENVIRONMENT_SCRIPT_DIRECTORY}" >&2; exit 1; }
 
   # Source common functions
   source ./src/ff_bash_functions || { echo "Error: failed to source ff_bash_functions common functions." >&2; exit 1; }
+  log "✅ sourced ff_bash_functions."
+
+  # Create ff_agent home directories - THIS IS WHERE THE INSTALLER CREATES THE FIRST DIRECTORIES
+  ff_agent_home_get_best
+  export FF_AGENT_HOME
+  [ -n "${FF_AGENT_HOME}" ] || { state_set "${FUNCNAME[0]}" "terminal_error_variable_ff_agent_home_not_set"; abort 'Failed to read FF_AGENT_HOME env var. ff_agent_home_get_best did not set it.'; }
+  mkdir -p "${FF_AGENT_HOME}" || { state_set "${FUNCNAME[0]}" "terminal_error_cant_create_home_directory"; abort 'terminal_error_cant_create_home_directory'; }
+  for DIR in bin state secrets applications git; do
+      mkdir -p "${FF_AGENT_HOME}/${DIR}" || { state_set "${FUNCNAME[0]}" "terminal_error_cant_create_${DIR}_directory"; abort "terminal_error_cant_create_${DIR}_directory"; }
+  done
 
   state_set "${FUNCNAME[0]}" 'started'
 
   # Initialize terminal
   terminal_initialize
 
-  # Create ff_agent home directories - THIS IS WHERE THE INSTALLER CREATES THE FIRST DIRECTORIES
-  ff_agent_home_get_best
-  [ -n "${FF_AGENT_HOME}" ] || { state_set "${FUNCNAME[0]}" "terminal_error_variable_ff_agent_home_not_set"; abort 'Failed to reaad FF_AGENT_HOME env var. ff_agent_home_get_best did not set it.'; }
-  mkdir -p "${FF_AGENT_HOME}" || { state_set "${FUNCNAME[0]}" "terminal_error_cant_create_home_directory"; abort 'terminal_error_cant_create_home_directory'; }
-  for DIR in bin state secrets applications git; do
-      mkdir -p "${FF_AGENT_HOME}/${DIR}" || { state_set "${FUNCNAME[0]}" "terminal_error_cant_create_${DIR}_directory"; abort "terminal_error_cant_create_${DIR}_directory"; }
-  done
-
   # Continue by calling OS-specific installer
   local OS
   OS="$( discover_os )"
-  OS_INSTALLER="./src/architecture/${OS}/continue_install.sh"
+  log "🟧 Discovered OS: ${OS}"
+  OS_INSTALLER="${SET_ENVIRONMENT_SCRIPT_DIRECTORY}/src/architecture/${OS}/continue_install.sh"
+  log "🟧 OS-specific installer script: ${OS_INSTALLER}"
   export OS_INSTALLER
 
   if [[ ! -f "$OS_INSTALLER" ]]; then
@@ -68,7 +74,7 @@ function install_set_environment () {
   fi
 
   # shellcheck disable=SC1090
-  source "$OS_INSTALLER" "${@}"
+  bash "$OS_INSTALLER" "${@}"
   SOURCE_EXIT_CODE=$?
 
   if [[ $SOURCE_EXIT_CODE -eq 0 ]]; then
