Many shellcheck lint fixes Working to make this work for Ubuntu 24.04 on host and in container

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,19 +1,12 @@
 #!/usr/bin/env bash
+# Install set_environment - Copyright (2018-2025) RedOKI
+
+# Do not run this script as root
+[ "$EUID" -ne 0 ] || { echo "❌ Do not run this script as root." >&2; exit 1; }
 
 # Enable tracing (more verbose output)
+export PS4='+ [$(date "+%H:%M:%S")] [${BASH_SOURCE##*/}:${LINENO}] [${FUNCNAME[0]:-MAIN}] '
 set -x
-
-# This script implements the installer logic of the "set_environment" project.
-# Project github page: https://github.com/redwolfsecurity/set_environment
-#
-# Caller must source this script, so it can inject environment into the current terminal as well.
-# To check the installation result one can use "set_environment_is_working" selfcheck function.
-# If installation succeed then selfcheck function will return success code 0.
-#
-# Caller can check if set_environment was started by the right user (after sourcing ". ./install")
-# by chkecking environment variable ${FF_AGENT_USERNAME}.
-#      Example: if [ "${FF_AGENT_USERNAME}" == "$(whoami)" ]; then echo "I'm the right/proper user"; fi
-#
 
 # Set optional SERVICE variable. If it is set, then it will be used:
 #  - as a tag for logger in log()
@@ -22,28 +15,78 @@ export SERVICE="set_environment"
 
 ###############################################################################
 #
-function install_set_environment {
-    # Can't state_set() here yet
-    # state_set "${FUNCNAME[0]}" 'started'
+# This function dynamically gets the directory the script is running in
+script_directory_get() {
+  local SOURCE="${BASH_SOURCE[0]}"
+  while [ -h "$SOURCE" ]; do
+    local DIR
+    DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"
+    SOURCE="$(readlink "$SOURCE")"
+    [[ "$SOURCE" != /* ]] && SOURCE="$DIR/$SOURCE"
+  done
+  cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd
+}
+export -f script_directory_get
 
-    # Change directory into the script's directory. This ensure all relative paths working correctly.
-    cd "$( dirname $( readlink -f "${BASH_SOURCE[0]}" ) )" || { echo "Error: failed to change directory to $( dirname ${BASH_SOURCE[0]} )" >&2; exit 1; } # note: can not yet use error() / abort() / state_set()
 
-    # Source common functions
-    source src/ff_bash_functions || { echo "Error: failed to source common functions." >&2; exit 1; } # note: can not yet use error() / abort() / state_set()
+###############################################################################
+#
+# shellcheck disable=SC2120
+function install_set_environment () {
+  # Bootstraping
 
-    # Initialize terminal
-    terminal_initialize || { state_set "${FUNCNAME[0]}" "terminal_error_initialize_terminal"; abort 'terminal_error_initialize_terminal'; }
+  # Change directory into the script's directory. This ensure all relative paths working correctly.
+  SET_ENVIRONMENT_SCRIPT_DIRECTORY="$( script_directory_get )"
+  export SET_ENVIRONMENT_SCRIPT_DIRECTORY
+  cd "${SET_ENVIRONMENT_SCRIPT_DIRECTORY}" || { echo "Error: failed to change directory to ${SET_ENVIRONMENT_SCRIPT_DIRECTORY}" >&2; exit 1; }
 
-    # Continue by calling OS-specific installer
-    source "src/architecture/$( discover_os )/continue_install.sh" "${@}" || { state_set "${FUNCNAME[0]}" "terminal_error_continue_install"; abort 'terminal_error_continue_install'; }
+  # Source common functions
+  source ./src/ff_bash_functions || { echo "Error: failed to source ff_bash_functions common functions." >&2; exit 1; }
 
-    # Last step: run a selfcheck
-    set_environment_is_working || { state_set "${FUNCNAME[0]}" "terminal_error_selfcheck_failed"; abort 'terminal_error_selfcheck_failed'; }
+  state_set "${FUNCNAME[0]}" 'started'
 
-    state_set "${FUNCNAME[0]}" 'success'
+  # Initialize terminal
+  terminal_initialize
+
+  # Create ff_agent home directories - THIS IS WHERE THE INSTALLER CREATES THE FIRST DIRECTORIES
+  ff_agent_home_get_best
+  [ -n "${FF_AGENT_HOME}" ] || { state_set "${FUNCNAME[0]}" "terminal_error_variable_ff_agent_home_not_set"; abort 'Failed to reaad FF_AGENT_HOME env var. ff_agent_home_get_best did not set it.'; }
+  mkdir -p "${FF_AGENT_HOME}" || { state_set "${FUNCNAME[0]}" "terminal_error_cant_create_home_directory"; abort 'terminal_error_cant_create_home_directory'; }
+  for DIR in bin state secrets applications git; do
+      mkdir -p "${FF_AGENT_HOME}/${DIR}" || { state_set "${FUNCNAME[0]}" "terminal_error_cant_create_${DIR}_directory"; abort "terminal_error_cant_create_${DIR}_directory"; }
+  done
+
+  # Continue by calling OS-specific installer
+  local OS
+  OS="$( discover_os )"
+  OS_INSTALLER="./src/architecture/${OS}/continue_install.sh"
+
+  if [[ ! -f "$OS_INSTALLER" ]]; then
+    state_set "${FUNCNAME[0]}" "terminal_error_missing_os_installer"
+    abort "Missing OS-specific installer script: ${OS_INSTALLER} (OS: ${OS})"
+  fi
+
+  # shellcheck disable=SC1090
+  source "$OS_INSTALLER" "${@}"
+  SOURCE_EXIT_CODE=$?
+
+  if [[ $SOURCE_EXIT_CODE -eq 0 ]]; then
+    state_set "${FUNCNAME[0]}" "sourced_os_installer_success"
+  elif [[ $SOURCE_EXIT_CODE -eq 2 ]]; then
+    state_set "${FUNCNAME[0]}" "terminal_error_syntax_in_installer"
+    abort "Syntax error or invalid command inside: ${OS_INSTALLER}"
+  else
+    state_set "${FUNCNAME[0]}" "terminal_error_runtime_in_installer_exit_${SOURCE_EXIT_CODE}"
+    abort "Installer script exited with non-zero status: ${SOURCE_EXIT_CODE}"
+  fi
+
+  # Last step: run a selfcheck
+  set_environment_is_working || { state_set "${FUNCNAME[0]}" "terminal_error_selfcheck_failed"; abort 'The install_set_environment final check of set_environment_is_working failed.'; }
+
+  state_set "${FUNCNAME[0]}" 'success'
 }
 
-install_set_environment  # no need to check errors here, the f-n itself reports errors (all of which are "terminal" errors) and aborts/exits.
+install_set_environment
 
+# Turn off tracing
 set +x
