Adding ff_docker_functions (containing all docker related functions, including new "docker_ensure())

diff --git a/src/ff_bash_functions b/src/ff_bash_functions
--- a/src/ff_bash_functions
+++ b/src/ff_bash_functions
@@ -11,7 +11,8 @@
 # https://stackoverflow.com/questions/1885871/exporting-a-function-in-shell
 # https://unix.stackexchange.com/questions/22796/can-i-export-functions-in-bash
 
-# Table of contents generated by function help_toc():
+# Table of contents generated by command:
+#    help_toc src/ff_bash_functions
 #
 ## BEGIN USAGE/HELP FUNCTION
 #    - ask_for_value 
@@ -47,8 +48,8 @@
 #    - get_by_url 
 #    - glob_matches 
 #    - inject_into_file 
+#    - path_to_absolute_path 
 #    - is_writable 
-#    - path_to_absolute_path
 #    - remove_all_lines_by_regexp 
 #    - replace_all_lines_by_regexp 
 #    - s 
@@ -82,14 +83,14 @@
 #    - is_process_running_as_me 
 ## END UTILITY FUNCTIONS: PROCESS
 ## BEGIN UTILITY FUNCTIONS: CONTAINERS
-#    - container_name_exists 
-#    - docker_cleanup
-#    - docker_volumes_to_containers_list
+#    - docker_container_name_exists 
+#    - docker_cleanup 
+#    - docker_volumes_to_containers_list 
 #    - get_installed_docker_version 
-#    - is_container_healthy 
-#    - is_container_running 
-#    - restart_containers 
-#    - stop_and_remove_container_by_name 
+#    - docker_is_container_healthy 
+#    - docker_is_container_running 
+#    - docker_restart_containers 
+#    - docker_stop_and_remove_container_by_name 
 ## END UTILITY FUNCTIONS: DOCKERS
 ## BEGIN UTILITY FUNCTIONS: STATE/SECRETS
 #    - generate_strong_password 
@@ -122,6 +123,7 @@
 #    - discover_required_environment_variable 
 #    - get_epoch_ms 
 #    - get_hardware_architecture 
+#    - get_os_name 
 #    - get_lsb_codename 
 #    - get_lsb_id 
 #    - get_lsb_id_downcase 
@@ -143,7 +145,6 @@
 #    - is_set_environment_working 
 #    - publish_message 
 ## END SET ENVIRONMENT FUNCTIONS
-
 
 ### BEGIN USAGE/HELP FUNCTION
 
@@ -505,6 +506,79 @@ export -f apt_upgrade
 ### END APT WRAPPER FUNCTIONS
 
 ### BEGIN UTILITY FUNCTIONS: STRINGS
+
+###############################################################################
+# Category: strings
+#
+# Given a version number MAJOR.MINOR.PATCH function get_version_component()
+# extracts one of three version components and prints it to standard output.
+#
+# Function return code:
+#   0 - on success
+#   1 - on error
+#
+# Usage examples:
+#   local VERSION="12.34.56"
+#   local MAJOR=$( get_version_component major "${VERSION}" ) || { set_state "${FUNCNAME[0]}" 'falied_to_extract_major_version'; return 1; }
+#   local MINOR=$( get_version_component minor "${VERSION}" ) || { set_state "${FUNCNAME[0]}" 'falied_to_extract_minor_version'; return 1; }
+#   local PATCH=$( get_version_component patch "${VERSION}" ) || { set_state "${FUNCNAME[0]}" 'falied_to_extract_patch_version'; return 1; }
+#
+function get_version_component {
+  set_state "${FUNCNAME[0]}" 'started'
+
+  # Check we get exactly 2 arguments
+  [ $# -eq 2 ] || { set_state "${FUNCNAME[0]}" 'error_wrong_number_of_arguments'; return 1; }
+
+  # Get arguments
+  local VERSION_COMPONENT_NAME="$1"
+  local FULL_VERSION="$2"
+
+  # Check we got non-empty arguments
+  [ ! -z ${VERSION_COMPONENT_NAME} ] || { set_state "${FUNCNAME[0]}" 'error_empty_argument_component_name'; return 1; }
+  [ ! -z ${FULL_VERSION} ] || { set_state "${FUNCNAME[0]}" 'error_empty_argument_full_version'; return 1; }
+
+  # Define an array of all supported version component names
+  local SUPPORTED_VERSION_COMPONENT_NAMES=("major" "minor" "patch")
+
+  # Check argument: must be 1 of 3 supported: major, minor, patch
+  if ! in_array "${VERSION_COMPONENT_NAME}" "${SUPPORTED_VERSION_COMPONENT_NAMES[@]}"; then
+    set_state "${FUNCNAME[0]}" 'error_unsupported_version_component_name'
+    return 1
+  fi
+
+  # Extract component version into EXTRACTED_COMPONENT_VERSION
+  case "${VERSION_COMPONENT_NAME}" in
+
+  major)
+    local EXTRACTED_COMPONENT_VERSION=$( echo "${FULL_VERSION}" | cut -d"." -f 1 )
+    ;;
+
+  minor)
+    local EXTRACTED_COMPONENT_VERSION=$( echo "${FULL_VERSION}" | cut -d"." -f 2 )
+    ;;
+
+  patch)
+    local EXTRACTED_COMPONENT_VERSION=$( echo "${FULL_VERSION}" | cut -d"." -f 3 )
+    ;;
+
+  *)
+    # We already checked (the value is in SUPPORTED_VERSION_COMPONENT_NAMES),
+    # but what if "case()" was not updated, then we must error out in our "default" case.
+    set_state "${FUNCNAME[0]}" 'error_unsupported_version_component_name_case'
+    return 1
+    ;;
+  esac
+  
+  # Check extracted EXTRACTED_COMPONENT_VERSION is not blank
+  [ ! -z "${EXTRACTED_COMPONENT_VERSION}" ] || { set_state "${FUNCNAME[0]}" 'error_got_empty_component_version'; return 1; }
+
+  # Print result to standard output
+  echo -n "${EXTRACTED_COMPONENT_VERSION}"
+
+  set_state "${FUNCNAME[0]}" 'success'
+  return 0
+}
+export -f get_version_component
 
 ###############################################################################
 # Category: strings
@@ -1866,243 +1940,6 @@ function is_process_running_as_me {
 export -f is_process_running_as_me
 
 ### END UTILITY FUNCTIONS: PROCESS
-
-
-### BEGIN UTILITY FUNCTIONS: CONTAINERS
-
-###############################################################################
-# Category: container
-# Utility function - Check if container exists
-#
-# Usage example:
-#    if container_name_exists "some_container_name"; then
-#       # Yes, container by given name does exist.
-#    else
-#       # No such container found
-#    fi
-#
-function container_name_exists {
-    CONTAINER_NAME="${1}"
-    # -z - true if the length of string is zero
-    # -n - true if the length of string is nonzero
-    if [ -z "${CONTAINER_NAME}" ]; then
-        error "error_no_container_name_specified"
-        return 2
-    fi
-    CONTAINER_ID=$(docker inspect --format="{{.Id}}" ${CONTAINER_NAME} 2> /dev/null)
-    if [[ "${CONTAINER_ID}" ]]; then
-        return 0
-    else
-        return 1
-    fi
-}
-export -f container_name_exists
-
-###############################################################################
-# Category: container
-# Utility function - Remove all unused containers, networks, images (both dangling and unreferenced)
-#
-# Function return code 0 on success, 1 on error (example: not enough permissions)
-#
-# Note: function also prints result to the standard output. 
-# Example: 
-#    Total reclaimed space: 0B
-#
-# TODO: And in that new function please add an error check. It is possible the docker system prune --al --force won't always work.
-# On some systems we might need to be root to run that command, so we will need to build out more robust docker functions that
-# might try one way vs. another and properly track what's going on.
-#
-function docker_cleanup {
-  set_state "${FUNCNAME[0]}" 'started'
-
-  # Cleanup some space
-  # docker system prune: Remove all unused containers, networks, images (both dangling and unreferenced), and optionally, volumes if --volumes used.
-  # Note: adding --volumes might be risky since it will erase DATA from stopped containers.
-  # More details: https://docs.docker.com/engine/reference/commandline/system_prune/
-  docker system prune --all --force || { set_state "${FUNCNAME[0]}" 'failed_to_docker_cleanup'; return 1; }
-
-  set_state "${FUNCNAME[0]}" 'success'
-  return 0
-}
-export -f docker_cleanup
-
-###############################################################################
-# Category: container
-# Utility function - Get list of volumes and print list of containers, which use them.
-#
-# TODO: improve it to also show the size of each volume by combining output from "docker system df --verbose"
-#
-function docker_volumes_to_containers_list {
-  set_state "${FUNCNAME[0]}" 'started'
-
-  # Get list of all docker volumes names
-  VOLUMES=$(docker volume ls  --format '{{.Name}}') || { set_state "${FUNCNAME[0]}" 'failed_to_list_docker_volumes'; return 1; }
-
-  # Iterate all volumes and check if i-th volume is used by any container (even if container is stopped)
-  for VOLUME in ${VOLUMES}; do
-    
-    # Simply print volume identifier
-    echo "${VOLUME}"
-
-    # Note: the following command will print associated container names prefixed with 2 spaces
-    docker ps -a --filter volume="${VOLUME}"  --format '{{.Names}}' | sed 's/^/  /'
-  done
-
-  set_state "${FUNCNAME[0]}" 'success'
-}
-export -f docker_volumes_to_containers_list
-
-###############################################################################
-# Category: container
-# Utility function - Get Docker Version
-function get_installed_docker_version {
-    DOCKER_PATH=$( command -v docker )
-    if [ -z "${DOCKER_PATH}" ]; then
-        return 1
-    else
-        DOCKER_VERSION=$( ${DOCKER_PATH} -v | cut -d" " -f 3 | cut -d"." -f 1 )
-        echo "${DOCKER_VERSION}"
-    fi
-}
-export -f get_installed_docker_version
-
-###############################################################################
-# Category: container
-# Utility function - Check if docker container healthy or not. This checks if the container is actually in the state 'running' vs. restarting
-function is_container_healthy {
-    CONTAINER_NAME="${1}"
-
-    # -z - true if the length of string is zero
-    # -n - true if the length of string is nonzero
-    if [ -z "${CONTAINER_NAME}" ]; then
-        error "error_no_container_name_specified"
-        return 2
-    fi
-    if [ "$( docker container inspect -f '{{.State.Status}}' ${CONTAINER_NAME} )" == "running" ]; then
-        return 0
-    else
-        return 1
-    fi
-}
-export -f is_container_healthy
-
-###############################################################################
-# Category: container
-# Utility function - Check if docker container running by given container name.
-# This checks if it is running, but it could be in a 'restart' loop.
-#
-# Return code:
-#   0 - container is running
-#   1 - container is not running
-#   2 - error: missing argument
-#
-function is_container_running {
-
-    # Take argument, check it is not empty
-    CONTAINER_NAME="${1}"
-    [ ! -z "${CONTAINER_NAME}" ] || { error "error_no_container_name_specified"; return 2; }
-
-    # Inspect given container, make sure it is in ranning state
-    if [ "$( docker container inspect -f '{{.State.Running}}' ${CONTAINER_NAME} )" == "true" ]; then
-        return 0
-    else
-        return 1
-    fi
-}
-export -f is_container_running
-
-###############################################################################
-# Category: container
-# Utility function - Restart docker containers
-function restart_containers {
-
-    # if [ -z "${@}" ]; then
-    #     error "error_no_container_names_specified"
-    #     return 2
-    # fi
-    CONTAINERS=(${@})
-    CONTAINERS_TO_RESTART=()
-    for CONTAINER in "${CONTAINERS[@]}"
-    do
-        # We only restart a container if it is defined
-        if container_name_exists "${CONTAINER}"
-        then
-            CONTAINERS_TO_RESTART+=( ${CONTAINER} )
-        fi
-    done
-
-    if (( ${#CONTAINERS_TO_RESTART[@]} )); then
-        docker restart ${CONTAINERS_TO_RESTART[@]}
-        return ${?}
-    fi
-
-    return 1
-}
-export -f restart_containers
-
-###############################################################################
-# Category: container
-# Utility function - Restart docker containers
-# Function gets container name (case sensitive) (can be partial) as the only input argument and
-# tries to find all matching containers (even if they're in stopped state). Then for every found
-# container it will "docker stop" and "docker remove" them.
-# Function return code 0 on success
-#
-function stop_and_remove_container_by_name {
-  set_state "${FUNCNAME[0]}" 'started'
-
-  CONTAINER_NAME="${1}"
-
-  # Check the container name isn't blank
-  [ "${CONTAINER_NAME}" != "" ] || { set_state "${FUNCNAME[0]}" 'error_bad_arguments'; return 1; }
-
-  # Count existing container(s) by given docker name
-  FOUND_CONTAINERS_COUNT=$( docker ps -a | grep "${CONTAINER_NAME}" | wc -l )
-
-  # Check if we found >1
-  if [ ${FOUND_CONTAINERS_COUNT} -gt 1 ]; then
-    # Yes, we found >1 containers to stop/remove
-    for DOCKER_ID in $(docker ps -a | grep "${CONTAINER_NAME}" | awk '{print $1}'); do
-      # Make sure DOCKER_ID is not a blank string
-      if [ "${DOCKER_ID}" == "" ]; then
-        set_state "${FUNCNAME[0]}" 'failed_to_get_docker_id'
-        return 1
-      fi
-
-      # Try to stop and remove the container
-      docker stop "${DOCKER_ID}"
-      docker rm "${DOCKER_ID}"
-
-      # Sometimes container can be in the broken state, in this case even after stopping and removing it
-      # the DOCKER_ID is still visible in the "docker ps" list. In this cas we need to kill -9 corresponding
-      # process on the host level:
-      STILL_PRESENT_DOCKER_ID=$( docker ps -a | grep "${DOCKER_ID}" | wc -l )
-      if [ "${STILL_PRESENT_DOCKER_ID}" != "" ]; then
-        # Yes, we have found "unstoppable" docker. Kill -9 the corresponding process now
-        PID_TO_KILL_COUNT=$( sudo ps aux | grep "${DOCKER_ID}" | wc -l )
-        PID_TO_KILL=$( sudo ps aux | grep "${DOCKER_ID}" )
-        if [ ${PID_TO_KILL_COUNT} -ne 1 ]; then
-          # Something went wrong, we supposed to find exactly ONE pid to terminate.
-          set_state "${FUNCNAME[0]}" 'failed_to_get_docker_pid'
-          return 1
-        fi
-
-        # Send "kill -9" signal to the found process
-        sudo kill -9 "${PID_TO_KILL}" || { set_state "${FUNCNAME[0]}" 'error_killing_process'; return 1; }
-
-        # The "unstoppable" docker terminated, now we can safely remove the container
-        docker rm "${DOCKER_ID}" || { set_state "${FUNCNAME[0]}" 'error_removing_docker'; return 1; }
-      fi
-    done
-
-  fi
-
-  set_state "${FUNCNAME[0]}" 'success'
-  return 0
-}
-export -f stop_and_remove_container_by_name
-
-### END UTILITY FUNCTIONS: DOCKERS
 
 
 ### BEGIN UTILITY FUNCTIONS: STATE/SECRETS
@@ -3760,7 +3597,7 @@ function is_set_environment_working {
     fi
   done
 
-  # TODO: check docker is installed with >= minimal version (if install_docker() was required in given environment)
+  # TODO: check docker is installed with >= minimal version (if the docker install was required in given environment)
 
   # TODO: check if list of required basic packages is installed
 
