Adding new f-n get_best_ff_port(). Preserving a set of other discussed environment values to add in future (see function discover_environment()).

diff --git a/src/ff_bash_functions b/src/ff_bash_functions
--- a/src/ff_bash_functions
+++ b/src/ff_bash_functions
@@ -14,117 +14,125 @@
 # Table of contents generated by function help_toc():
 #
 ## BEGIN USAGE/HELP FUNCTION
-#    - ask_for_value
-#    - ask_for_yn
-#    - command_exists
-#    - file_toc
-#    - help
-#    - help_toc
+#    - ask_for_value 
+#    - ask_for_yn 
+#    - command_exists 
+#    - file_toc 
+#    - help 
+#    - help_toc 
 ## END USAGE/HELP FUNCTION
 ## BEGIN APT WRAPPER FUNCTIONS
-#    - apt_install
-#    - apt_list
-#    - apt_reinstall
-#    - apt_remove
-#    - apt_update
-#    - apt_upgrade
-#    - apt_dist_upgrade
+#    - apt_dist_upgrade 
+#    - apt_install 
+#    - apt_list 
+#    - apt_reinstall 
+#    - apt_remove 
+#    - apt_update 
+#    - apt_upgrade 
 ## END APT WRAPPER FUNCTIONS
 ## BEGIN UTILITY FUNCTIONS: STRINGS
-#    - in_array
-#    - index_of
-#    - parse_github_repository_url
-#    - trim_slash
+#    - in_array 
+#    - index_of 
+#    - parse_github_repository_url 
+#    - trim_slash 
 ## END UTILITY FUNCTIONS: STRINGS
 ## BEGIN UTILITY FUNCTIONS: FILE
-#    - assert_cd
-#    - assert_makedir
-#    - does_file_have_eol_at_the_end
-#    - f
-#    - file_contains_pattern
-#    - find_file_owner_in_all_packages
-#    - find_file_owner_in_installed_packages
-#    - get_by_url
-#    - glob_matches
-#    - inject_into_file
-#    - is_writable
-#    - remove_all_lines_by_regexp
-#    - replace_all_lines_by_regexp
-#    - s
-#    - truncate_file
+#    - assert_cd 
+#    - assert_makedir 
+#    - does_file_have_eol_at_the_end 
+#    - f 
+#    - file_contains_pattern 
+#    - find_file_owner_in_all_packages 
+#    - find_file_owner_in_installed_packages 
+#    - get_by_url 
+#    - glob_matches 
+#    - inject_into_file 
+#    - is_writable 
+#    - remove_all_lines_by_regexp 
+#    - replace_all_lines_by_regexp 
+#    - s 
+#    - truncate_file 
 ## END UTILITY FUNCTIONS: FILE
 ## BEGIN UTILITY FUNCTIONS: LOGGING / PROCESS CONTROl
-#    - abort
-#    - assert_clean_exit
-#    - error
-#    - log
-#    - successful_exit
-#    - warning
+#    - abort 
+#    - assert_clean_exit 
+#    - error 
+#    - log 
+#    - successful_exit 
+#    - warning 
 ## END UTILITY FUNCTIONS: LOGGING / PROCESS CONTROl
 ## BEGIN UTILITY FUNCTIONS: TERMINAL / SHELL
-#    - ensure_variable_defined
-#    - ensure_variable_not_empty
-#    - is_shell_attribute_set
-#    - is_shell_option_set
-#    - terminal_initialize
-#    - terminal_is_interactive
-#    - terminal_is_tty
-#    - terminal_reset
+#    - ensure_variable_defined 
+#    - ensure_variable_not_empty 
+#    - is_shell_attribute_set 
+#    - is_shell_option_set 
+#    - terminal_initialize 
+#    - terminal_is_interactive 
+#    - terminal_is_tty 
+#    - terminal_reset 
 ## END UTILITY FUNCTIONS: TERMINAL / SHELL
 ## BEGIN UTILITY FUNCTIONS: PROCESS
-#    - is_process_running_as_me
+#    - is_process_running_as_me 
 ## END UTILITY FUNCTIONS: PROCESS
 ## BEGIN UTILITY FUNCTIONS: CONTAINERS
-#    - container_name_exists
-#    - get_installed_docker_version
-#    - is_container_healthy
-#    - is_container_running
-#    - restart_containers
-#    - stop_and_remove_container_by_name
+#    - container_name_exists 
+#    - get_installed_docker_version 
+#    - is_container_healthy 
+#    - is_container_running 
+#    - restart_containers 
+#    - stop_and_remove_container_by_name 
 ## END UTILITY FUNCTIONS: DOCKERS
 ## BEGIN UTILITY FUNCTIONS: STATE/SECRETS
-#    - generate_strong_password
-#    - get_secret
-#    - get_state
-#    - set_secret
-#    - set_state
+#    - generate_strong_password 
+#    - get_secret 
+#    - get_state 
+#    - set_secret 
+#    - set_state 
 ## END UTILITY FUNCTIONS: STATE/SECRETS
 ## BEGIN UTILITY FUNCTIONS: USER / GROUPS
-#    - can_sudo
-#    - check_group_exists
-#    - create_user
-#    - effectively_root
-#    - get_home_directory_for_user
-#    - get_ppid_cmd
-#    - is_user_in_group
-#    - user_exists
+#    - can_sudo 
+#    - check_group_exists 
+#    - create_user 
+#    - effectively_root 
+#    - get_home_directory_for_user 
+#    - get_ppid_cmd 
+#    - is_user_in_group 
+#    - user_exists 
 ## END UTILITY FUNCTIONS: USER / GROUPS
 ## BEGIN DISCOVER FUNTIONS
-#    - get_best_ff_content_url
-#    - discover_environment
-#    - discover_optional_environment_variable
-#    - discover_os
-#    - discover_required_environment_variable
-#    - get_epoch_ms
-#    - get_hardware_architecture
-#    - get_lsb_codename
-#    - get_lsb_id
-#    - get_lsb_release
+#    - ff_uuid 
+#    - get_best_ff_agent_uri 
+#    - get_best_ff_content_url 
+#    - get_best_ff_host 
+#    - get_best_ff_port 
+#    - get_best_namespace 
+#    - get_best_organization 
+#    - discover_environment 
+#    - discover_optional_environment_variable 
+#    - discover_os 
+#    - discover_required_environment_variable 
+#    - get_epoch_ms 
+#    - get_hardware_architecture 
+#    - get_lsb_codename 
+#    - get_lsb_id 
+#    - get_lsb_id_downcase 
+#    - get_lsb_release 
 ## END DISCOVER FUNCTIONS
 ## BEGIN SET ENVIRONMENT FUNCTIONS
-#    - check_environment_variables_are_set
-#    - check_set_get_state
-#    - check_set_get_secret
-#    - check_nodejs_installation
-#    - check_ff_agent_bin_is_in_the_path
-#    - choose_ff_agent_home
-#    - ensure_ff_agent_home_exists
-#    - ff_api_get
-#    - get_ff_agent_username
-#    - get_expected_nodejs_version
-#    - is_framework_api_defined
-#    - is_set_environment_working
-#    - publish_message
+#    - check_environment_variables_are_set 
+#    - check_ff_agent_bin_is_in_the_path 
+#    - check_nodejs_installation 
+#    - check_set_get_secret 
+#    - check_set_get_state 
+#    - get_current_user 
+#    - choose_ff_agent_home 
+#    - ensure_ff_agent_home_exists 
+#    - ff_api_get 
+#    - get_expected_nodejs_version 
+#    - get_ff_agent_username 
+#    - is_framework_api_defined 
+#    - is_set_environment_working 
+#    - publish_message 
 ## END SET ENVIRONMENT FUNCTIONS
 
 
@@ -1835,7 +1843,7 @@ export -f generate_strong_password
 # Utility function, getting secret value by given secret key name.
 # Note: get_secret() require the FF_AGENT_HOME to be set.
 function get_secret {
-
+  
   # Dependency check: 'tr' is installed
   if ! command_exists tr >/dev/null; then
     set_state "${FUNCNAME[0]}" 'error_dependency_not_met_tr'
@@ -1846,6 +1854,8 @@ function get_secret {
   if is_shell_attribute_set x; then
     XTRACE_WAS_ENABLED=true
   fi
+
+  set_state "${FUNCNAME[0]}" 'started'
 
   set +x # Disble xtrace to avoid priting secrets
 
@@ -2507,7 +2517,7 @@ export -f get_best_ff_content_url
 #   - on failure: return code 1
 #
 # Usage example:
-#  FF_HOST=$( get_best_ff_host )
+#  UPLOAD_TO=$( get_best_ff_host )
 #  [ $? -eq 0 ] || { set_state "${FUNCNAME[0]}" "failed_to_get_best_ff_host"; return 1; }
 #
 function get_best_ff_host {
@@ -2531,41 +2541,29 @@ export -f get_best_ff_host
 
 ###############################################################################
 #
-# Figure out environment - where are we?
-# Function sets secrets (by set_secret f-n calls), which stores them under ${FF_AGENT_HOME}/secrets/ folder.
-# Function also sets corresponding environment variables:
-#     - is_container,
-#     - is_portal,
-#     - is_local,
-#     - is_traffic_generator
-#     - ff_agent_uri
-#     - ff_host
-#     - namespace
-#     - organization
-#     - ff_api_username
-#     - ff_api_password
+# Auxiliary function wraps the logic of choosing the best value for: 'FF_HOST'
+# Note: this function uses get/set secrets and state, thus it can be called only after "choose proper user" step is complete.
 #
-# Note: The discover_environment() step must check if the above variables are set (exist in environment),
-# if not, then it must check those by the "get_secret()". This step discovers values (no "mkdir" or any other actions taken).
+# Function return:
+#   - on success: return code 0 and choosen value printed to standard outout
+#   - on failure: return code 1
 #
-function get_best_ff_host {
+function get_best_ff_port {
   set_state "${FUNCNAME[0]}" 'started'
+  FF_PORT_DEFAULT=443
 
-  # Try to get value from environment or by get_secret()
-  discover_optional_environment_variable "FF_HOST" || { set_state "${FUNCNAME[0]}" "failed_to_discover_optional_environment_variable_ff_host"; return 1; } # Note: FF_HOST: FF_HOST will be set to legacy portal hostname if this is a portal.
+  # Try to get FF_PORT from environment or by get_secret()
+  discover_optional_environment_variable "FF_PORT" || { set_state "${FUNCNAME[0]}" "failed_to_discover_optional_environment_variable_ff_port"; return 1; }
 
-  # Check if variable already set. If not try to get it's value by command 'hostname'
-  [ -z "${FF_HOST}" ] && { FF_HOST="$( hostname )"; }
-
-  # Make sure the variable is now not empty or error out.
-  ensure_variable_not_empty 'FF_HOST' || { set_state "${FUNCNAME[0]}" "error_ensure_variable_not_empty_ff_host"; return 1; }
+  # Check if variable already set. If not then use default
+  [ -z "${FF_PORT}" ] && { FF_PORT="${FF_PORT_DEFAULT}"; }
 
   # Print result to standard output, set state to 'success' and return success code.
-  echo "${FF_HOST}"
+  echo "${FF_PORT}"
   set_state "${FUNCNAME[0]}" 'success'
   return 0
 }
-export -f get_best_ff_host
+export -f get_best_ff_port
 
 ###############################################################################
 #
@@ -2648,6 +2646,15 @@ function discover_environment {
   #  [x] ORGANIZATION (see get_best_organization())
   #  [x] TERM  (see terminal_initialize())
   #
+  # Preserving a set of other discussed environment values to add in future:
+  #  FF_PROTOCOL
+  #  FF_API_TOKEN
+  #  FF_PROXY_HOST
+  #  FF_PROXY_PORT
+  #  FF_PROXY_PROTOCOL
+  #  FF_PROXY_USERNAME
+  #  FF_PROXY_PASSWORD
+  #
   choose_ff_agent_home || { abort "failed_to_choose_ff_agent_home"; }
   ensure_ff_agent_home_exists || { abort "failed_to_ensure_ff_agent_home_exists"; }
 
@@ -2674,6 +2681,10 @@ function discover_environment {
   FF_HOST=$( get_best_ff_host )               || { abort "failed_to_get_best_ff_host"; }
   set_secret ff_host "${FF_HOST}"
   export FF_HOST
+
+  FF_PORT=$( get_best_ff_port )               || { abort "failed_to_get_best_ff_port"; }
+  set_secret ff_port "${FF_PORT}"
+  export FF_PORT
 
   # ######################################################################
   # # Discover set of "ff environment" variables
