Reduced some logging on echos for check_dependencies and state_set

diff --git a/src/ff_bash_functions b/src/ff_bash_functions
--- a/src/ff_bash_functions
+++ b/src/ff_bash_functions
@@ -2952,11 +2952,9 @@ export -f terminal_reset
 #
 ###############################################################################
 function check_dependencies {
-    # Save current shell options
-    local SHELL_OPTIONS_OLD
-    SHELL_OPTIONS_OLD="$(set +o)"
-    # Disable tracing
-    set +x
+    BASH_ECHO_SETTINGS=$( bash_echo_setting_get ) || { error "${FUNCNAME[0]}" 'failed_to_bash_echo_setting_gets'; return 1; }
+
+    bash_echo_off_set || { error "${FUNCNAME[0]}" 'failed_to_bash_echo_off_set'; return 1; } # Disable xtrace to avoid priting secrets
 
     # Get 1st argument: caller function name
     local CALLER_FUNCTION_NAME="${1}"
@@ -2972,16 +2970,16 @@ function check_dependencies {
     # Ensure the caller function name is provided
     if [[ -z "${CALLER_FUNCTION_NAME}" ]]; then
         # Restore old shell options
-        eval "${SHELL_OPTIONS_OLD}"
         error "${CALLER_FUNCTION_NAME}" "CALLER_FUNCTION_NAME must not be empty"
+        bash_echo_setting_set "${BASH_ECHO_SETTINGS}"
         return 1
     fi
 
     # Ensure there is at least one dependency to check
     if [[ ${#DEPENDENCIES[@]} -eq 0 ]]; then
         # Restore old shell options
-        eval "${SHELL_OPTIONS_OLD}"
         error "${CALLER_FUNCTION_NAME}" "At least one dependency must be specified"
+        bash_echo_setting_set "${BASH_ECHO_SETTINGS}"
         return 1
     fi
 
@@ -3002,18 +3000,16 @@ function check_dependencies {
         # Convert the array to a string with spaces separating elements
         local MISSING_LIST=$(IFS=' ' ; echo "${MISSING_DEPENDENCIES[*]}")
         if [[ "${MISSING_DEPENDENCY_COUNT}" -eq 1 ]]; then
-            # Restore old shell options
-            eval "${SHELL_OPTIONS_OLD}"
             error "${CALLER_FUNCTION_NAME}" "Dependency not met: ${MISSING_LIST}"
+            bash_echo_setting_set "${BASH_ECHO_SETTINGS}"
         else
-            # Restore old shell options
-            eval "${SHELL_OPTIONS_OLD}"
             error "${CALLER_FUNCTION_NAME}" "Dependencies not met: ${MISSING_LIST}"
+            bash_echo_setting_set "${BASH_ECHO_SETTINGS}"
         fi
         return 1
     fi
     # Restore old shell options
-    eval "${SHELL_OPTIONS_OLD}"
+    bash_echo_setting_set "${BASH_ECHO_SETTINGS}"
 }
 
 # Export the function if you need to use it in scripts sourced from this script
@@ -3671,12 +3667,11 @@ export -f state_get
 #
 ###############################################################################
 function state_set {
-# Save current shell options
-  local OLD_SHELL_OPTS
-  OLD_SHELL_OPTS="$(set +o)"
 
-  # Disable tracing
-  set +x
+  # Preserve current bash echo settings and enable bash echo setting
+  BASH_ECHO_SETTINGS=$( bash_echo_setting_get ) || { error "${FUNCNAME[0]}" 'failed_to_bash_echo_setting_gets'; return 1; }
+
+  bash_echo_off_set || { error "${FUNCNAME[0]}" 'failed_to_bash_echo_off_set'; return 1; } # Disable xtrace to avoid priting secrets
 
   # Check dependencies
   local DEPENDENCIES=(
@@ -3690,7 +3685,7 @@ function state_set {
     "command_exists"
   )
   check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {
-    eval "${OLD_SHELL_OPTS}"
+    bash_echo_setting_set "${BASH_ECHO_SETTINGS}"  # Restore bash echo settings
     return 1
   }  # Note: check_dependencies will report missing dependencies
 
@@ -3699,17 +3694,17 @@ function state_set {
   local STATE_VALUE="${2}"
 
   # Check state name / value aren't blank
-  [ -n "${STATE_NAME}" ] || { error "state_set(): blank state name argument"; eval "${OLD_SHELL_OPTS}"; return 1; }
-  [ -n "${STATE_VALUE}" ] || { error "state_set(): blank state value argument"; eval "${OLD_SHELL_OPTS}"; return 1; }
+  [ -n "${STATE_NAME}" ] || { error "state_set(): blank state name argument"; bash_echo_setting_set "${BASH_ECHO_SETTINGS}"; return 1; }
+  [ -n "${STATE_VALUE}" ] || { error "state_set(): blank state value argument"; bash_echo_setting_set "${BASH_ECHO_SETTINGS}"; return 1; }
 
   # Check if state name / vaue contains any prohibited symbols, then error out.
-  [[ ! "${STATE_NAME}" =~ ([^a-z0-9_]+) ]] || { error "state_set(): illegal characters in the state name argument: '${BASH_REMATCH[1]}'"; eval "${OLD_SHELL_OPTS}"; return 1; }
-  [[ ! "${STATE_VALUE}" =~ ([^a-z0-9_]+) ]] || { error "state_set(): illegal characters in the state value argument: '${BASH_REMATCH[1]}'"; eval "${OLD_SHELL_OPTS}"; return 1; }
+  [[ ! "${STATE_NAME}" =~ ([^a-z0-9_]+) ]] || { error "state_set(): illegal characters in the state name argument: '${BASH_REMATCH[1]}'"; bash_echo_setting_set "${BASH_ECHO_SETTINGS}"; return 1; }
+  [[ ! "${STATE_VALUE}" =~ ([^a-z0-9_]+) ]] || { error "state_set(): illegal characters in the state value argument: '${BASH_REMATCH[1]}'"; bash_echo_setting_set "${BASH_ECHO_SETTINGS}"; return 1; }
 
   # Make sure "${FF_AGENT_HOME}" is not empty
   if [ -z "${FF_AGENT_HOME}" ]; then
       error "Can not set state. FF_AGENT_HOME variable not set. State would have been set to ${STATE_NAME}=${STATE_VALUE}"
-      eval "${OLD_SHELL_OPTS}"
+      bash_echo_setting_set "${BASH_ECHO_SETTINGS}"
       return 1
   fi
 
@@ -3720,7 +3715,7 @@ function state_set {
 
     mkdir -p "${STATE_DIR}" || {
       error "Can not set state. State directory ${STATE_DIR} can not be created. State would have been set to ${STATE_NAME}=${STATE_VALUE}"
-      eval "${OLD_SHELL_OPTS}"
+      bash_echo_setting_set "${BASH_ECHO_SETTINGS}"
       return 1
     }
   fi
@@ -3731,9 +3726,11 @@ function state_set {
   # Write value into the file
   echo "${STATE_VALUE}" >"${STATE_FILE}" || {
     error "${FUNCNAME[0]}: failed_to_write_state. State would have been set to ${STATE_NAME}=${STATE_VALUE}"
-    eval "${OLD_SHELL_OPTS}"
+    bash_echo_setting_set "${BASH_ECHO_SETTINGS}"
     return 1
   }
+
+  echo "${FUNCNAME[0]}: state ${STATE_NAME} set to ${STATE_VALUE}"
 
   # ------------------ Build JSON object "state/change" and send to FF_AGENT_API_FQDN
 
@@ -3745,7 +3742,7 @@ function state_set {
     # No, the framework API is not defined. Simply return, we're done.
     # Return with success code 0
     echo "${FUNCNAME[0]}: framework API is not defined, skipping state/change message."
-    eval "${OLD_SHELL_OPTS}"
+    bash_echo_setting_set "${BASH_ECHO_SETTINGS}"
     return 1
   fi
 
@@ -3762,14 +3759,14 @@ function state_set {
   local TIMESTAMP_EPOCH_MS
   TIMESTAMP_EPOCH_MS="$( epoch_ms_get )" || {
     error "${FUNCNAME[0]}: failed to get time by calling epoch_ms_get()"
-    eval "${OLD_SHELL_OPTS}"
+    bash_echo_setting_set "${BASH_ECHO_SETTINGS}"
     return 1
     }
 
   # Check if we actually got non-empty string?
   [ -n "${TIMESTAMP_EPOCH_MS}" ] || {
     error "${FUNCNAME[0]}: got empty timestamp_epoch_ms value"
-    eval "${OLD_SHELL_OPTS}"
+    bash_echo_setting_set "${BASH_ECHO_SETTINGS}"
     return 1
   }
 
@@ -3802,7 +3799,7 @@ function state_set {
   local UUID
   UUID="$( ff_uuid )" || {
     error "${FUNCNAME[0]}" 'failed_generate_uuid'
-    eval "${OLD_SHELL_OPTS}"
+    bash_echo_setting_set "${BASH_ECHO_SETTINGS}"
     return 1
   }
 
@@ -3885,7 +3882,7 @@ EOF
   fi
 
   # Restore shell options
-  eval "${OLD_SHELL_OPTS}"
+  bash_echo_setting_set "${BASH_ECHO_SETTINGS}"
 }
 export -f state_set
 
