Moving service_is_running() from continue_install.functions.sh to ff_bash_functions. Reasons: (1) it is generic and useful, (2) it is used in docker_install() and listed as a dependency.

diff --git a/src/ff_bash_functions b/src/ff_bash_functions
--- a/src/ff_bash_functions
+++ b/src/ff_bash_functions
@@ -3133,6 +3133,51 @@ function retry_command {
 }
 export -f retry_command
 
+###############################################################################
+# CATEGORY
+#   UTILITY FUNCTIONS: PROCESS
+#
+# NAME
+#   service_is_running - Checks if a service by a given name is running.
+#
+# SYNOPSIS
+#   service_is_running service_name
+#
+# DESCRIPTION
+#   Checks if the specified service is currently active (running). This function
+#   is useful for script logic that depends on the state of system services.
+#   It returns a code indicating the status (0 for running, non-zero for not running or error).
+#
+# EXAMPLES
+#   # Check if the 'docker' service is running
+#   if service_is_running docker; then
+#     echo "Docker is running."
+#   else
+#     echo "Docker is not running."
+#   fi
+#
+# EXIT STATUS
+#   0 - Service is running.
+#   Non-zero - Service is not running or an error occurred.
+#
+###############################################################################
+function service_is_running {
+
+  # Check dependencies
+  local DEPENDENCIES="systemctl error"
+  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES}" || return 1  # Note: check_dependencies will report missing dependencies
+
+  # Take arguments
+  local SERVICE_NAME="$1"
+
+  # Check arguments (must be non-empty string)
+  [ ! -z "${SERVICE_NAME}" ] || { error "${FUNCNAME[0]}" 'error_empty_argument'; return 1; }
+
+  # Do the check
+  systemctl is-active --quiet "${SERVICE_NAME}"
+}
+export -f service_is_running
+
 ### END UTILITY FUNCTIONS: PROCESS
 
 
